### ISSUE TITLE
Containers, microservices, and service meshes

### ISSUE THREAD

**Issue by yangchuansheng** [servicemesher/weekly#302]
## 类型

本文的类型为：翻译

## 文章信息

- 原文链接：https://jpetazzo.github.io/2019/05/17/containers-microservices-service-meshes/

- 原文发布时间：2019 年 5 月 17 日

- 作者： jpetazzo

- 标签：Istio, kubernetes, servicemesh, envoy

## 当前进度

- [x] 已提交文章线索
- [x] 已有人认领翻译或为原创文章
- [ ] 已提交 PR
- [ ] 正在review
- [ ] review 完成等待发布
- [ ] 已发布到 http://www.servicemesher.com
- [ ] 已发布到 ServiceMesher 微信公众号

**Comment by GuangmingLuo** [comment]
accept

**Comment by GuangmingLuo** [comment]
请到https://github.com/servicemesher/website/issues重新提一次issue。
